# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'product_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(779, 600)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_fiche = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.edit_fiche.setMinimumSize(QtCore.QSize(531, 0))
        self.edit_fiche.setObjectName("edit_fiche")
        self.horizontalLayout.addWidget(self.edit_fiche)
        self.frame_infos = QtWidgets.QFrame(self.centralwidget)
        self.frame_infos.setMaximumSize(QtCore.QSize(181, 16777215))
        self.frame_infos.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_infos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_infos.setObjectName("frame_infos")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_infos)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_prod = QtWidgets.QFrame(self.frame_infos)
        self.frame_prod.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_prod.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_prod.setObjectName("frame_prod")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_prod)
        self.verticalLayout.setObjectName("verticalLayout")
        self.prod_label_name = QtWidgets.QLabel(self.frame_prod)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prod_label_name.setFont(font)
        self.prod_label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.prod_label_name.setObjectName("prod_label_name")
        self.verticalLayout.addWidget(self.prod_label_name)
        self.prod_label_id = QtWidgets.QLabel(self.frame_prod)
        font = QtGui.QFont()
        font.setItalic(True)
        self.prod_label_id.setFont(font)
        self.prod_label_id.setAlignment(QtCore.Qt.AlignCenter)
        self.prod_label_id.setObjectName("prod_label_id")
        self.verticalLayout.addWidget(self.prod_label_id)
        self.prod_label_source = QtWidgets.QLabel(self.frame_prod)
        font = QtGui.QFont()
        font.setItalic(True)
        self.prod_label_source.setFont(font)
        self.prod_label_source.setAlignment(QtCore.Qt.AlignCenter)
        self.prod_label_source.setObjectName("prod_label_source")
        self.verticalLayout.addWidget(self.prod_label_source)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.prod_layout_cds = QtWidgets.QHBoxLayout()
        self.prod_layout_cds.setObjectName("prod_layout_cds")
        self.prod_label_cds = QtWidgets.QLabel(self.frame_prod)
        self.prod_label_cds.setObjectName("prod_label_cds")
        self.prod_layout_cds.addWidget(self.prod_label_cds)
        self.prod_label_cds_value = QtWidgets.QLabel(self.frame_prod)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.prod_label_cds_value.setFont(font)
        self.prod_label_cds_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prod_label_cds_value.setObjectName("prod_label_cds_value")
        self.prod_layout_cds.addWidget(self.prod_label_cds_value)
        self.verticalLayout.addLayout(self.prod_layout_cds)
        self.prod_layout_length = QtWidgets.QHBoxLayout()
        self.prod_layout_length.setObjectName("prod_layout_length")
        self.prod_label_length = QtWidgets.QLabel(self.frame_prod)
        self.prod_label_length.setObjectName("prod_label_length")
        self.prod_layout_length.addWidget(self.prod_label_length)
        self.prod_label_length_value = QtWidgets.QLabel(self.frame_prod)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prod_label_length_value.setFont(font)
        self.prod_label_length_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prod_label_length_value.setObjectName("prod_label_length_value")
        self.prod_layout_length.addWidget(self.prod_label_length_value)
        self.verticalLayout.addLayout(self.prod_layout_length)
        self.prod_layout_weight = QtWidgets.QHBoxLayout()
        self.prod_layout_weight.setObjectName("prod_layout_weight")
        self.prod_label_weight = QtWidgets.QLabel(self.frame_prod)
        self.prod_label_weight.setObjectName("prod_label_weight")
        self.prod_layout_weight.addWidget(self.prod_label_weight)
        self.prod_label_weight_value = QtWidgets.QLabel(self.frame_prod)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prod_label_weight_value.setFont(font)
        self.prod_label_weight_value.setAlignment(QtCore.Qt.AlignCenter)
        self.prod_label_weight_value.setObjectName("prod_label_weight_value")
        self.prod_layout_weight.addWidget(self.prod_label_weight_value)
        self.verticalLayout.addLayout(self.prod_layout_weight)
        self.prod_layout_complete = QtWidgets.QHBoxLayout()
        self.prod_layout_complete.setObjectName("prod_layout_complete")
        self.prod_label_complete = QtWidgets.QLabel(self.frame_prod)
        self.prod_label_complete.setObjectName("prod_label_complete")
        self.prod_layout_complete.addWidget(self.prod_label_complete)
        self.prod_label_complete_value = QtWidgets.QLabel(self.frame_prod)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prod_label_complete_value.setFont(font)
        self.prod_label_complete_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prod_label_complete_value.setObjectName("prod_label_complete_value")
        self.prod_layout_complete.addWidget(self.prod_label_complete_value)
        self.verticalLayout.addLayout(self.prod_layout_complete)
        self.prod_layout_pred = QtWidgets.QHBoxLayout()
        self.prod_layout_pred.setObjectName("prod_layout_pred")
        self.prod_label_pred = QtWidgets.QLabel(self.frame_prod)
        self.prod_label_pred.setObjectName("prod_label_pred")
        self.prod_layout_pred.addWidget(self.prod_label_pred)
        self.prod_label_pred_value = QtWidgets.QLabel(self.frame_prod)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prod_label_pred_value.setFont(font)
        self.prod_label_pred_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prod_label_pred_value.setObjectName("prod_label_pred_value")
        self.prod_layout_pred.addWidget(self.prod_label_pred_value)
        self.verticalLayout.addLayout(self.prod_layout_pred)
        self.prod_label_notes = QtWidgets.QLabel(self.frame_prod)
        self.prod_label_notes.setObjectName("prod_label_notes")
        self.verticalLayout.addWidget(self.prod_label_notes)
        self.prod_label_note_value = QtWidgets.QLabel(self.frame_prod)
        font = QtGui.QFont()
        font.setItalic(True)
        self.prod_label_note_value.setFont(font)
        self.prod_label_note_value.setObjectName("prod_label_note_value")
        self.verticalLayout.addWidget(self.prod_label_note_value)
        self.verticalLayout_4.addWidget(self.frame_prod)
        spacerItem1 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.frame_esp = QtWidgets.QFrame(self.frame_infos)
        self.frame_esp.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_esp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_esp.setObjectName("frame_esp")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_esp)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.esp_label_name = QtWidgets.QLabel(self.frame_esp)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.esp_label_name.setFont(font)
        self.esp_label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.esp_label_name.setObjectName("esp_label_name")
        self.verticalLayout_2.addWidget(self.esp_label_name)
        self.esp_label_statut = QtWidgets.QLabel(self.frame_esp)
        font = QtGui.QFont()
        font.setItalic(True)
        self.esp_label_statut.setFont(font)
        self.esp_label_statut.setAlignment(QtCore.Qt.AlignCenter)
        self.esp_label_statut.setObjectName("esp_label_statut")
        self.verticalLayout_2.addWidget(self.esp_label_statut)
        self.esp_layout_button = QtWidgets.QHBoxLayout()
        self.esp_layout_button.setObjectName("esp_layout_button")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.esp_layout_button.addItem(spacerItem2)
        self.esp_button_open = QtWidgets.QPushButton(self.frame_esp)
        self.esp_button_open.setObjectName("esp_button_open")
        self.esp_layout_button.addWidget(self.esp_button_open)
        self.verticalLayout_2.addLayout(self.esp_layout_button)
        self.verticalLayout_4.addWidget(self.frame_esp)
        spacerItem3 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.frame_app = QtWidgets.QFrame(self.frame_infos)
        self.frame_app.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_app.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_app.setObjectName("frame_app")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_app)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_app = QtWidgets.QLabel(self.frame_app)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_app.setFont(font)
        self.label_app.setAlignment(QtCore.Qt.AlignCenter)
        self.label_app.setObjectName("label_app")
        self.verticalLayout_3.addWidget(self.label_app)
        self.checkBox_1 = QtWidgets.QCheckBox(self.frame_app)
        self.checkBox_1.setChecked(True)
        self.checkBox_1.setObjectName("checkBox_1")
        self.verticalLayout_3.addWidget(self.checkBox_1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_app)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_app)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_3.addWidget(self.checkBox_3)
        self.app_layout_button = QtWidgets.QHBoxLayout()
        self.app_layout_button.setObjectName("app_layout_button")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.app_layout_button.addItem(spacerItem4)
        self.app_button_modif = QtWidgets.QPushButton(self.frame_app)
        self.app_button_modif.setObjectName("app_button_modif")
        self.app_layout_button.addWidget(self.app_button_modif)
        self.verticalLayout_3.addLayout(self.app_layout_button)
        self.verticalLayout_4.addWidget(self.frame_app)
        self.horizontalLayout.addWidget(self.frame_infos)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.prod_label_name.setText(_translate("MainWindow", "Nom produit"))
        self.prod_label_id.setText(_translate("MainWindow", "Identifiant"))
        self.prod_label_source.setText(_translate("MainWindow", "Source"))
        self.prod_label_cds.setText(_translate("MainWindow", "CDS"))
        self.prod_label_cds_value.setText(_translate("MainWindow", "1 - 100"))
        self.prod_label_length.setText(_translate("MainWindow", "Taille : "))
        self.prod_label_length_value.setText(_translate("MainWindow", "100 pb"))
        self.prod_label_weight.setText(_translate("MainWindow", "Poids moleculaire :"))
        self.prod_label_weight_value.setText(_translate("MainWindow", "30 kd"))
        self.prod_label_complete.setText(_translate("MainWindow", "Complete :"))
        self.prod_label_complete_value.setText(_translate("MainWindow", "oui"))
        self.prod_label_pred.setText(_translate("MainWindow", "Predicted"))
        self.prod_label_pred_value.setText(_translate("MainWindow", "non"))
        self.prod_label_notes.setText(_translate("MainWindow", "Notes :"))
        self.prod_label_note_value.setText(_translate("MainWindow", "Predicted by Gnomon"))
        self.esp_label_name.setText(_translate("MainWindow", "Nom espèce"))
        self.esp_label_statut.setText(_translate("MainWindow", "Statut IUCN"))
        self.esp_button_open.setText(_translate("MainWindow", "Ouvrir"))
        self.label_app.setText(_translate("MainWindow", "Applications"))
        self.checkBox_1.setText(_translate("MainWindow", "Biotechnologie"))
        self.checkBox_2.setText(_translate("MainWindow", "Pharmaceutique"))
        self.checkBox_3.setText(_translate("MainWindow", "Cosmétologie"))
        self.app_button_modif.setText(_translate("MainWindow", "Modifier"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
